version: '3'

services: 
  frontend: 
    build: .
    environment: 
      - NODE_ENV=development
    volumes: 
      - ./:/usr/src/fire-app
    command: sh -c 'cd frontend && yarn start'
    ports: 
      - '8080:8080'
    tty: true